name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |   
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

    - name: Build the Docker Image
      run: |
        docker build -t yairmarin/docker-graphq:0.0.2 .
        docker build -t yairmarin/docker-graphq:latest .

    - name: Docker Push
      run: |
        docker push yairmarin/docker-graphq:0.0.2
        docker push yairmarin/docker-graphq:latest